In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('C:/Users/micronet computers/Desktop/Scikit Learn/Titanic.csv', index_col=0)
df.shape

(891, 11)

In [3]:
df.columns

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
df.isnull().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [5]:
df = df.loc[df.Embarked.notnull(),['Survived','Sex','Pclass','Embarked']]

In [6]:
df = df.reset_index(drop=True)

In [7]:
df.head()

Survived     Sex  Pclass Embarked
0         0    male       3        S
1         1  female       1        C
2         1  female       3        S
3         1  female       1        S
4         0    male       3        S

In [8]:
df.isnull().sum()

Survived    0
Sex         0
Pclass      0
Embarked    0
dtype: int64

In [9]:
df.head()

Survived     Sex  Pclass Embarked
0         0    male       3        S
1         1  female       1        C
2         1  female       3        S
3         1  female       1        S
4         0    male       3        S

In [10]:
X = df.loc[:,['Pclass']]
y = df.Survived

In [11]:
X.shape

(889, 1)

In [12]:
y.shape

(889,)

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
logreg = LogisticRegression()

In [15]:
from sklearn.model_selection import cross_val_score

In [16]:
score = cross_val_score(logreg, X, y, cv=5, scoring='accuracy')

In [17]:
score.mean()

0.6783406335301212

In [18]:
y.value_counts(normalize=True)

0    0.617548
1    0.382452
Name: Survived, dtype: float64

In [19]:
df.head()

Survived     Sex  Pclass Embarked
0         0    male       3        S
1         1  female       1        C
2         1  female       3        S
3         1  female       1        S
4         0    male       3        S

In [20]:
from sklearn.preprocessing import OneHotEncoder

In [21]:
ohe = OneHotEncoder(sparse=False)

In [22]:
ohe.fit_transform(df[['Sex']])

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [0., 1.]])

In [23]:
ohe.categories_

[array(['female', 'male'], dtype=object)]

In [24]:
df.head()

Survived     Sex  Pclass Embarked
0         0    male       3        S
1         1  female       1        C
2         1  female       3        S
3         1  female       1        S
4         0    male       3        S

In [25]:
X = df.drop(['Survived'],axis=1)

In [26]:
X.head()

Sex  Pclass Embarked
0    male       3        S
1  female       1        C
2  female       3        S
3  female       1        S
4    male       3        S

In [27]:
from sklearn.compose import make_column_transformer

In [28]:
column_trans = make_column_transformer(
    (OneHotEncoder(), ['Sex','Embarked']), 
    remainder='passthrough')

In [29]:
column_trans.fit_transform(X)

array([[0., 1., 0., 0., 1., 3.],
       [1., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 3.],
       ...,
       [1., 0., 0., 0., 1., 3.],
       [0., 1., 1., 0., 0., 1.],
       [0., 1., 0., 1., 0., 3.]])

In [30]:
from sklearn.pipeline import make_pipeline

In [31]:
pipe = make_pipeline(column_trans, logreg)

In [32]:
cross_val_score(pipe, X, y, cv=5, scoring='accuracy').mean()

0.7727924839713071

In [33]:
X_new = X.sample(5, random_state=99)

In [34]:
X_new

Sex  Pclass Embarked
598    male       1        C
511    male       1        S
272    male       1        C
214  female       1        C
789    male       3        Q

In [35]:
pipe.fit(X,y)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(),
                                                  ['Sex', 'Embarked'])])),
                ('logisticregression', LogisticRegression())])

In [36]:
pipe.predict(X_new)

array([1, 0, 1, 1, 0], dtype=int64)