In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [20]:
df = pd.read_csv('C:/Users/micronet computers/Desktop/Projects/Machine Learning/Car Driving 2.csv')
df

Speed  Age  Experience  Risk
0    200   15         5.0    85
1     90   17        13.0    20
2    165   12         4.0    92
3    110   20         NaN    60
4    140    5         3.0    82
5    115    2         8.0    10

In [21]:
df['Experience'] = df['Experience'].fillna(df.Experience.mean())
df

Speed  Age  Experience  Risk
0    200   15         5.0    85
1     90   17        13.0    20
2    165   12         4.0    92
3    110   20         6.6    60
4    140    5         3.0    82
5    115    2         8.0    10

In [23]:
feature_columns = ['Speed','Age','Experience']
X = df[feature_columns]
X.shape

(6, 3)

In [24]:
y = df.Risk
y.shape

(6,)

In [25]:
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(X,y)

LinearRegression()

In [27]:
linreg.predict([[160,10,5]])

array([71.3336032])

In [28]:
linreg.coef_

array([ 0.19847984,  2.15248065, -7.8012218 ])

In [29]:
linreg.intercept_

57.05813198563225

In [30]:
linreg.predict([[150,4,10]])

array([17.42781193])

### Performance